name: Vaultix CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Build client
        working-directory: ./client
        run: npm run build